In [9]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('./dataset/cluster1_6.csv')
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])

# 선박별 + 항구별 소요 시간 계산
duration_df = (
    df.groupby(['VSL_ID', 'PORT_NAME'])['TIMESTAMP']
    .agg(['min', 'max'])
    .reset_index()
)
duration_df['DURATION_HOURS'] = (duration_df['max'] - duration_df['min']).dt.total_seconds() / 3600
duration_df = duration_df[['VSL_ID', 'PORT_NAME', 'DURATION_HOURS']]

# 상위 20개만 보기
from IPython.display import display
display(duration_df)

                                  VSL_ID PORT_NAME  DURATION_HOURS
0   0359a9fc-db7a-3187-9550-f9a3b3c90f37     CNQDG       45.166667
1   05e4d21a-31a0-3476-adf8-792558757ade     CNDAG       62.000000
2   06724e0f-5a08-3aa8-b42c-97acf4f8102d     CNQDG       34.833333
3   1019badb-0b17-306b-a41f-ecef79dd1886     CNQDG       45.833333
4   2a5bff79-dfe1-3221-b9f0-126b5917c784     CNQDG       51.166667
5   2a9cf20b-d0fe-3684-bca9-a0c279842dde     CNQDG       45.833333
6   37154f3b-a9d2-36b4-bcf2-e8b9fcea9d11     CNQDG       54.333333
7   40f54b8d-c327-3b37-97fa-41fa6ffc92a7     CNQDG       64.333333
8   422b3a51-0494-3706-9769-8f96f6063853     CNQDG       45.000000
9   42c578a0-ce4c-3cf7-977e-ece463542581     CNDAG       68.666667
10  42c578a0-ce4c-3cf7-977e-ece463542581     CNLYG       37.500000
11  44b2cfd2-26bb-3deb-8169-8e16eb98b842     CNQDG       40.000000
12  485929b5-0963-33d9-ae84-d7d2ed8dd715     CNQDG       72.166667
13  4e27bc10-d1ec-356b-8d56-9050c7fa3cb4     CNQDG       33.666667
14  50e853cf-e6ee-322c-8897-f24837c8465d     CNQDG       71.333333
15  52a7cda9-1bcd-379d-a6dc-e1dbceb6c8b4     CNLYG       40.833333
16  52a7cda9-1bcd-379d-a6dc-e1dbceb6c8b4     CNRZH       38.666667
17  52c28360-1122-3a3b-9655-3fd0ba2559a6     CNQDG       35.333333
18  5fc05863-b4d9-30c2-aec1-91c5c74cc50d     CNQDG       38.166667
19  615046a4-ea69-377a-b3a9-f9927165f9e4     CNLYG       42.833333
20  69d53028-a21c-3c8a-8a26-ec9ffc4bed0a     CNLYG       37.000000
21  69d53028-a21c-3c8a-8a26-ec9ffc4bed0a     CNRZH       50.666667
22  7021f725-de58-334f-a0d8-f2b5debf8fac     CNQDG       57.833333
23  7489e60a-7a4c-35fc-b57a-9c07f76fa1d2     CNTXG      170.333333
24  771e4fc5-8f81-3f95-bc47-6fdc9d2c7dec     CNLYG      124.666667
25  77d4b59d-3d1f-3c92-8ed3-aa4fa86d43a3     CNRZH       48.333333
26  77d4b59d-3d1f-3c92-8ed3-aa4fa86d43a3     CNTXG       63.833333
27  828015af-b98d-38e5-88b3-b415db600e74     CNQDG       88.333333
28  8b82b41b-cb03-316e-997d-64825bf584ae     CNQDG       32.666667
29  8bb32b1c-e699-3fe5-a503-29e2f45a060d     CNQDG       40.833333
30  9987edb3-523e-3e81-aef4-fb9de8b0e887     CNQDG       42.166667
31  9b439131-371b-3f06-865f-993f5c269f91     CNLYG       43.000000
32  9b439131-371b-3f06-865f-993f5c269f91     CNRZH       78.000000
33  9c29a353-ad4e-3a25-b2ca-e3163e080d69     CNLYG       44.500000
34  9c29a353-ad4e-3a25-b2ca-e3163e080d69     CNQDG       87.333333
35  9e1b8dba-4f4d-34f2-9e5f-10b55afb360e     CNQDG       39.000000
36  9e5ff808-986c-3318-8b72-a76463fa1726     CNQDG       36.333333
37  9faa6003-17ab-3412-896e-04eb09f6c434     CNTXG       51.666667
38  a56fb1ad-c1f2-37fc-a383-99f8ba4caf01     CNLYG       47.166667
39  a804036f-9377-3242-a11d-1b76dfa0dcec     CNDAG       52.833333
40  a804036f-9377-3242-a11d-1b76dfa0dcec     CNLYG       46.833333
41  a90fba15-f1f6-39c2-aa96-838e326eacc5     CNTXG       44.833333
42  b6c76089-d161-39f9-8e7d-a5d80ba32791     CNLYG       36.833333
43  beb5c997-3574-3ead-88de-cc0035c4d0db     CNLYG       75.000000
44  c1645e91-304d-34cc-849f-5fd4b20d1cdc     CNQDG       81.166667
45  c3662709-01de-3365-9de3-478fc8884654     CNQDG       89.833333
46  c4a0ea1d-e999-3b21-b394-521a19c74c8b     CNDAG       78.000000
47  c5e964f8-4254-3970-8b6f-7bb4a976c438     CNQDG       43.166667
48  c85b6aa8-befa-316e-b80b-fb5f70c4b7ff     CNTXG       48.166667
49  ca42f39b-9eba-3fa7-89ea-dc9a7546c025     CNLYG       35.166667
50  cf8263b9-d3a1-386e-80c0-e74fb265f6d9     CNQDG       62.333333
51  d57cef5a-948d-32e0-9121-c2123c011ee7     CNQDG       44.000000
52  d57cef5a-948d-32e0-9121-c2123c011ee7     CNTXG       80.000000
53  ed99782b-2acc-3d95-a6df-2ac584955537     CNTXG       72.333333
54  f8231099-7293-30bd-a780-3af96d75f816     CNTXG       51.833333
55  f86be205-4f5a-3e36-b44a-78a85e00fc05     CNQDG       48.833333
56  fbfb850e-e85f-353d-9d1c-16e523878977     CNLYG       45.666667

In [2]:
import pandas as pd

# CSV 파일 불러오기
file_path = "./dataset/must_use_final.csv"
df = pd.read_csv(file_path)

# 데이터프레임의 기본 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151756 entries, 0 to 151755
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  151756 non-null  int64
 1   COUNTRY     151756 non-null  object
 2   PORT_NAME   151756 non-null  object
 3   VSL_ID      151756 non-null  object
 4   TIMESTAMP   151756 non-null  object
 5   COG         151756 non-null  float64
 6   HEADING     151756 non-null  float64
 7   LAT         151756 non-null  float64
 8   LON         151756 non-null  float64
 9   PORT_CD     151756 non-null  object
 10  CLUSTER_1   151756 non-null  int64
 11  CLUSTER_2   151756 non-null  int64
dtypes: float64(4), int64(3), object(5)
memory usage: 13.9+ MB

In [16]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 1. 데이터 불러오기
df = pd.read_csv("./dataset/cluster1_1.csv")

df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df = df.sort_values(by=['VSL_ID', 'PORT_NAME', 'TIMESTAMP']).reset_index(drop=True)

# 결과 저장 리스트
rows_5h = []

# 30번째 시점 추출 (10분 단위 (1시간 - 6개) × 30 = 5시간)
for (vsl_id, port), group in df.groupby(['VSL_ID', 'PORT_NAME']):
    if len(group) >= 84:
        row_5h = group.iloc[83]  # 인덱스는 0부터 시작이므로 29번째가 30번째 행
        rows_5h.append(row_5h)

# 최종 데이터프레임
df_5h = pd.DataFrame(rows_5h).reset_index(drop=True)
print(df_5h.shape)
display(df_5h.head())
display(df_5h['PORT_NAME'].value_counts())


# 14시간 시점 데이터를 구하기 위해, 각 그룹별로 첫 시점 기준 offset이 14시간인 데이터 추출
def extract_14h_exact_row(group):
    if len(group) > 84:
        return group.iloc[[83]]  # 0부터 시작이므로 84번째는 index 83
    else:
        return pd.DataFrame()  # 84번째 데이터가 없으면 무시

# VSL_ID와 PORT_NAME을 기준으로 그룹화하여 14시간 시점 데이터 추출
grouped = df_sorted.groupby(['VSL_ID', 'PORT_NAME'], group_keys=False)
data_14h = grouped.apply(extract_14h_data)

# 군집별(=CLUSTER_1) 데이터 개수 확인
extract_14h_exact_row = data_14h['CLUSTER_1'].value_counts().sort_index()

extract_14h_exact_row

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35887 entries, 0 to 35886
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   COUNTRY    35887 non-null  object
 1   PORT_NAME  35887 non-null  object
 2   VSL_ID     35887 non-null  object
 3   TIMESTAMP  35887 non-null  object
 4   COG        35887 non-null  float64
 5   HEADING    35887 non-null  float64
 6   LAT        35887 non-null  float64
 7   LON        35887 non-null  float64
 8   PORT_CD    35887 non-null  object
 9   CLUSTER_1  35887 non-null  int64
 10  CLUSTER_2  35887 non-null  int64
dtypes: float64(4), int64(2), object(5)
memory usage: 3.0+ MB

C:\Users\user\AppData\Local\Temp\ipykernel_6928\122528568.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_14h = grouped.apply(extract_14h_data)

CLUSTER_1
1    377
Name: count, dtype: int64

In [8]:
port_14h_counts = data_14h['PORT_NAME'].value_counts().sort_index()
port_14h_counts

PORT_NAME
CNDAG      4
CNHUA      7
CNLYG     13
CNNGB     11
CNNJI      4
CNQDG     28
CNRZH      4
CNSHA     72
CNTAC      4
CNTXG      8
HKHKG     10
JPHIJ      8
JPHKT      8
JPIMB      3
JPIMI      3
JPKIJ     11
JPMKX      3
JPMOJ      4
JPNGO      5
JPNGS      3
JPOSA     11
JPSMZ     14
JPTYO     15
JPUKB     13
JPWAK      3
JPYKK      4
JPYOK     14
KRINC     29
KRKAN    113
KRKPO     19
KRPTK     10
KRYOS     45
PHMNL      4
RUNJK      4
RUVVO     21
TWKEL     10
TWKHH      5
VNHPH      9
Name: count, dtype: int64

In [10]:
cluster_port_14h_counts = data_14h.groupby(['CLUSTER_1', 'PORT_NAME']).size().reset_index(name='count')

cluster_port_14h_counts

    CLUSTER_1 PORT_NAME  count
0           0     PHMNL      4
1           1     JPHIJ      8
2           1     JPHKT      8
3           1     JPIMB      3
4           1     JPIMI      3
5           1     JPMOJ      4
6           1     JPNGS      3
7           1     KRINC     29
8           1     KRKAN    113
9           1     KRKPO     19
10          1     KRPTK     10
11          1     KRYOS     45
12          2     CNNGB     11
13          2     CNNJI      4
14          2     CNSHA     72
15          2     CNTAC      4
16          3     JPKIJ     11
17          3     JPMKX      3
18          3     JPNGO      5
19          3     JPOSA     11
20          3     JPSMZ     14
21          3     JPTYO     15
22          3     JPUKB     13
23          3     JPWAK      3
24          3     JPYKK      4
25          3     JPYOK     14
26          4     CNHUA      7
27          4     HKHKG     10
28          4     TWKEL     10
29          4     TWKHH      5
30          5     VNHPH      9
31          6     CNDAG      4
32          6     CNLYG     13
33          6     CNQDG     28
34          6     CNRZH      4
35          6     CNTXG      8
36          7     RUNJK      4
37          7     RUVVO     21

In [12]:
under_3_ports = cluster_port_14h_counts[cluster_port_14h_counts['count'] <= 3]

# 해당 항구의 개수 출력
num_under_3_ports = under_3_ports['PORT_NAME'].nunique()
num_under_3_ports

5

In [25]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 1. 데이터 불러오기
df = pd.read_csv("./dataset/must_use_final.csv")

# 2. TIMESTAMP 형식 변환 및 정렬
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df = df.sort_values(by=['VSL_ID', 'PORT_NAME', 'TIMESTAMP']).reset_index(drop=True)

# 4. 14시간 시점(=84번째 행)만 추출
rows_14h = []
for key, group in df.groupby('VSL_ID'):
    if len(group) >= 84:
        row_14h = group.iloc[83]
        rows_14h.append(row_14h)

df_14h = pd.DataFrame(rows_14h).reset_index(drop=True)

# 5. 군집별 항구별 개수 집계
grouped_detail = df_14h.groupby(['CLUSTER_1', 'PORT_NAME']).size().reset_index(name='port_count')

# 6. 군집별 총 개수 집계
grouped_total = df_14h.groupby('CLUSTER_1').size().reset_index(name='cluster_total')

# 7. 병합하여 최종 결과 생성
result_df = pd.merge(grouped_detail, grouped_total, on='CLUSTER_1')

# 8. 결과 출력
print(result_df)

    CLUSTER_1 PORT_NAME  port_count  cluster_total
0           0     PHMNL           2              2
1           1     JPHIJ           8             71
2           1     JPIMB           2             71
3           1     JPNGS           1             71
4           1     KRINC          20             71
5           1     KRKAN          14             71
6           1     KRKPO           4             71
7           1     KRPTK           3             71
8           1     KRYOS          19             71
9           2     CNNGB          11             80
10          2     CNNJI           3             80
11          2     CNSHA          64             80
12          2     CNTAC           2             80
13          3     JPKIJ           3             38
14          3     JPMKX           1             38
15          3     JPNGO           3             38
16          3     JPOSA           6             38
17          3     JPSMZ          11             38
18          3     JPTYO           5             38
19          3     JPUKB           6             38
20          3     JPYKK           1             38
21          3     JPYOK           2             38
22          4     CNHUA           7             30
23          4     HKHKG           9             30
24          4     TWKEL           9             30
25          4     TWKHH           5             30
26          5     VNHPH           5              5
27          6     CNDAG           4             48
28          6     CNLYG          11             48
29          6     CNQDG          26             48
30          6     CNRZH           1             48
31          6     CNTXG           6             48
32          7     RUNJK           2             12
33          7     RUVVO          10             12

In [41]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 1. 데이터 불러오기
df = pd.read_csv("./dataset/must_use_final.csv")

# 2. TIMESTAMP 형식 변환 및 정렬
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df = df.sort_values(by=['VSL_ID', 'PORT_NAME', 'TIMESTAMP']).reset_index(drop=True)

# 3. 선박 + 항구 조합으로 고유 식별자 생성
df['VSL_PORT_KEY'] = df['VSL_ID'] + "_" + df['PORT_NAME']

# 4. 각 그룹별로 84번째(=14시간 시점) 데이터 추출
rows_14h = []
for key, group in df.groupby('VSL_PORT_KEY'):
    if len(group) >= 84:
        row_14h = group.iloc[83]
        rows_14h.append(row_14h)

df_14h = pd.DataFrame(rows_14h).reset_index(drop=True)

# 5. 군집별 항구별 개수 및 군집 총합 계산
grouped_detail = df_14h.groupby(['CLUSTER_1', 'PORT_NAME']).size().reset_index(name='count_14h')
grouped_total = df_14h.groupby('CLUSTER_1').size().reset_index(name='cluster_total')
merged = pd.merge(grouped_detail, grouped_total, on='CLUSTER_1')

# 6. 군집명에 총합 붙이기
merged['CLUSTER_1_LABEL'] = merged.apply(
    lambda row: f"CLUSTER_1 = {row['CLUSTER_1']} (총 {row['cluster_total']}개)", axis=1
)

# 7. 보기 좋게 출력
grouped_print_data = merged.groupby('CLUSTER_1_LABEL')

for cluster_label, group in grouped_print_data:
    print(f"👉 {cluster_label}")
    print(group[['PORT_NAME', 'count_14h']].to_string(index=False))
    print()

👉 CLUSTER_1 = 0 (총 4개)
PORT_NAME  count_14h
    PHMNL          4

👉 CLUSTER_1 = 1 (총 96개)
PORT_NAME  count_14h
    JPHIJ          8
    JPIMB          3
    JPIMI          1
    JPMOJ          2
    JPNGS          2
    KRINC         29
    KRKAN         19
    KRKPO          2
    KRPTK         10
    KRYOS         20

👉 CLUSTER_1 = 2 (총 91개)
PORT_NAME  count_14h
    CNNGB         11
    CNNJI          4
    CNSHA         72
    CNTAC          4

👉 CLUSTER_1 = 3 (총 93개)
PORT_NAME  count_14h
    JPKIJ         11
    JPMKX          3
    JPNGO          5
    JPOSA         11
    JPSMZ         14
    JPTYO         15
    JPUKB         13
    JPWAK          3
    JPYKK          4
    JPYOK         14

👉 CLUSTER_1 = 4 (총 32개)
PORT_NAME  count_14h
    CNHUA          7
    HKHKG         10
    TWKEL         10
    TWKHH          5

👉 CLUSTER_1 = 5 (총 9개)
PORT_NAME  count_14h
    VNHPH          9

👉 CLUSTER_1 = 6 (총 57개)
PORT_NAME  count_14h
    CNDAG          4
    CNLYG         13
    CNQDG         28
    CNRZH          4
    CNTXG          8

👉 CLUSTER_1 = 7 (총 25개)
PORT_NAME  count_14h
    RUNJK          4
    RUVVO         21

In [48]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 1. 데이터 불러오기 (군집 1만 포함된 파일)
df = pd.read_csv("./dataset/cluster1_6.csv")

# 2. TIMESTAMP 정렬
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df = df.sort_values(by=['VSL_ID', 'PORT_NAME', 'TIMESTAMP']).reset_index(drop=True)

# 3. 선박+도착항구 조합별로 그룹핑 후 84번째(=14시간) 시점 추출
rows_14h = []
for (vsl_id, port), group in df.groupby(['VSL_ID', 'PORT_NAME']):
    if len(group) >= 84:
        row_14h = group.iloc[83]
        rows_14h.append(row_14h)

df_14h = pd.DataFrame(rows_14h).reset_index(drop=True)

# 4. 항구별 개수 계산
port_counts = df_14h['PORT_NAME'].value_counts().reset_index()
port_counts.columns = ['PORT_NAME', 'count_14h']

# 5. 총합 계산
total = port_counts['count_14h'].sum()

# 6. 예쁘게 출력
print(f"📦 CLUSTER_1 = 1 (총 {total}개)")
print(port_counts.to_string(index=False))

📦 CLUSTER_1 = 1 (총 57개)
PORT_NAME  count_14h
    CNQDG         28
    CNLYG         13
    CNTXG          8
    CNDAG          4
    CNRZH          4